// Detailed weapon information for the BF1942 Wiki

export interface DetailedWeapon {
    id: string;
    name: string;
    category: 'Sidearm' | 'SMG' | 'Assault Rifle' | 'Rifle' | 'Sniper' | 'Anti-Tank' | 'Explosive';
    affiliation: 'Allies' | 'Axis' | 'Both';
    kit: string;
    nationality: string;
    mechanism: string;
    magCapacity: number;
    totalAmmo: string;
    effectiveRange: string;
    historicalContext: string;
    inGamePerformance: string;
    tacticalAnalysis: string;
}

export const detailedWeapons: DetailedWeapon[] = [
    // === SIDEARMS ===
    {
        id: 'colt-m1911',
        name: 'Colt M1911A1',
        category: 'Sidearm',
        affiliation: 'Allies',
        kit: 'All Kits',
        nationality: 'US, UK, USSR, Canada',
        mechanism: 'Semi-automatic, recoil-operated',
        magCapacity: 7,
        totalAmmo: '42-63 rounds',
        effectiveRange: 'Short (0-50m)',
        historicalContext: 'The M1911A1 is the quintessential American service pistol, chambered in .45 ACP. Renowned for its stopping power, it served as the standard-issue sidearm for US forces throughout the 20th century.',
        inGamePerformance: 'The universal sidearm for all Allied factions. Characterized by a 7-round magazine capacity. The damage model typically requires three body shots or two headshots to neutralize an opponent. Recoil animation is snappy, allowing rapid follow-up shots, though accuracy degrades if fired at maximum speed.',
        tacticalAnalysis: 'Indispensable for the Anti-Tank class. After firing a Bazooka rocket, the long reload time leaves you vulnerable; quickly switching to the Colt allows engagement of rushing infantry. Also the primary defense for Scouts relocating between positions.',
    },
    {
        id: 'walther-p38',
        name: 'Walther P38',
        category: 'Sidearm',
        affiliation: 'Axis',
        kit: 'All Kits',
        nationality: 'Germany, Japan',
        mechanism: 'Semi-automatic, short-recoil',
        magCapacity: 8,
        totalAmmo: '48-64 rounds',
        effectiveRange: 'Short (0-50m)',
        historicalContext: 'The Walther P38 replaced the Luger P08 as the standard service pistol of the Wehrmacht. Chambered in 9x19mm Parabellum, it was the first locked-breech pistol to use a double-action/single-action trigger.',
        inGamePerformance: 'The Axis counterpart to the Colt with an 8-round magazine, granting a +1 round capacity advantage. Damage per round is marginally lower than the .45 ACP Colt, but the difference is negligible in most combat scenarios.',
        tacticalAnalysis: 'The extra round in the magazine can be the deciding factor in pistol duels. Japanese forces also use the P38 in the base game (historically they would use the Nambu Type 14), likely due to asset reuse during development.',
    },

    // === SUBMACHINE GUNS ===
    {
        id: 'thompson-m1a1',
        name: 'Thompson M1A1',
        category: 'SMG',
        affiliation: 'Allies',
        kit: 'Medic',
        nationality: 'US, UK, Canada',
        mechanism: 'Blowback-operated',
        magCapacity: 30,
        totalAmmo: '180 rounds (6 mags)',
        effectiveRange: 'Short-Medium (0-75m)',
        historicalContext: 'The "Tommy Gun" was a symbol of Allied firepower. The M1A1 military variant simplified the design for mass production, utilizing a 30-round box magazine instead of the heavy drum magazines used by gangsters.',
        inGamePerformance: 'A powerhouse in close-quarters combat. Features a 30-round magazine and high rate of fire. Iron sights are open and unobtrusive, making target tracking easy. Suffers from moderate damage drop-off at long ranges.',
        tacticalAnalysis: 'On maps like Omaha Beach or Stalingrad, the Thompson allows Medics to clear bunkers and ruins effectively. The 30-round capacity is generous, allowing engagement of multiple targets without reloading.',
    },
    {
        id: 'mp40',
        name: 'MP40',
        category: 'SMG',
        affiliation: 'Axis',
        kit: 'Medic',
        nationality: 'Germany',
        mechanism: 'Straight blowback',
        magCapacity: 32,
        totalAmmo: '192 rounds (6 mags)',
        effectiveRange: 'Short-Medium (0-100m)',
        historicalContext: 'The MP40 was the standard SMG of the German army, heavily used by paratroopers and squad leaders. It pioneered the use of stamped steel parts and a folding stock.',
        inGamePerformance: 'Renowned for its stability with a 32-round magazine. Rate of fire is slower (~500 RPM) than the Thompson, which translates to lower recoil and greater controllability during sustained fire.',
        tacticalAnalysis: 'The MP40\'s stability makes it superior to the Thompson at medium range. German Medics can harass infantry across streets or open fields where the Thompson\'s spread would be too high.',
    },
    {
        id: 'mp18',
        name: 'MP18',
        category: 'SMG',
        affiliation: 'Both',
        kit: 'Medic',
        nationality: 'Japan, USSR',
        mechanism: 'Blowback-operated',
        magCapacity: 32,
        totalAmmo: '192 rounds (6 mags)',
        effectiveRange: 'Short-Medium (0-100m)',
        historicalContext: 'Originally a WWI German weapon. Its presence for Soviet and Japanese troops is an anachronism used to fill the SMG slot for factions lacking unique assets in the base game (the PPSh-41 and Type 100 appear in expansions).',
        inGamePerformance: 'Functionally mimics the MP40 but uses a side-mounted "stick" magazine. The side-mounted magazine can obscure a portion of the screen, a minor disadvantage compared to the bottom-feeding MP40.',
        tacticalAnalysis: 'For Soviet Medics on Berlin or Kharkov, this weapon requires aggressive positioning to compensate for the lack of the Assault class\'s range. Serves as the primary close-defense tool against German infantry.',
    },

    // === ASSAULT RIFLES / LMGs ===
    {
        id: 'stg44',
        name: 'StG 44',
        category: 'Assault Rifle',
        affiliation: 'Axis',
        kit: 'Assault',
        nationality: 'Germany',
        mechanism: 'Gas-operated, tilting bolt',
        magCapacity: 30,
        totalAmmo: '150 rounds (5 mags)',
        effectiveRange: 'Medium-Long (0-400m)',
        historicalContext: 'The world\'s first true assault rifle. The StG 44 combined the automatic fire of an SMG with the range of a rifle, firing the intermediate 7.92x33mm Kurz cartridge.',
        inGamePerformance: 'Widely regarded as the best infantry weapon in the standard game. Features a 30-round magazine and excellent accuracy. Unlike the Allied BAR with its small magazine, the StG 44 can sustain fire, suppressing multiple enemies or pre-firing corners.',
        tacticalAnalysis: 'Gives German Assault troops a distinct advantage. Its versatility allows it to function as an SMG in bunkers and a rifle in the fields, creating tactical flexibility that Allied forces struggle to match.',
    },
    {
        id: 'bar-m1918',
        name: 'BAR M1918A2',
        category: 'Assault Rifle',
        affiliation: 'Allies',
        kit: 'Assault',
        nationality: 'US, UK',
        mechanism: 'Gas-operated',
        magCapacity: 20,
        totalAmmo: '100 rounds (5 mags)',
        effectiveRange: 'Medium-Long (0-300m)',
        historicalContext: 'The BAR was intended as a "walking fire" weapon for trench warfare. In WWII, it served as the squad automatic weapon.',
        inGamePerformance: 'Defined by its limitation: a 20-round magazine. While damage per bullet is high (reflecting the .30-06 cartridge), the small magazine depletes rapidly (under 3 seconds of continuous fire). Forces a "shoot-and-scoot" playstyle.',
        tacticalAnalysis: 'Allied Assault players must practice trigger discipline. Engaging more than two targets without reloading is risky. Best used for precise bursts at medium range rather than suppression.',
    },
    {
        id: 'dp28',
        name: 'DP-28',
        category: 'Assault Rifle',
        affiliation: 'Allies',
        kit: 'Assault',
        nationality: 'USSR',
        mechanism: 'Gas-operated, flap-locking',
        magCapacity: 47,
        totalAmmo: '141 rounds (3 mags)',
        effectiveRange: 'Medium-Long (0-300m)',
        historicalContext: 'The standard Soviet LMG, known for its distinctive pan magazine.',
        inGamePerformance: 'The Soviet answer to the LMG role. Its defining feature is the 47-round pan magazine, offering more than double the capacity of the BAR. Allows for true suppressive fire. Reload time is lengthy and the large pan obscures the lower center of view.',
        tacticalAnalysis: 'On Eastern Front maps, the DP-28 allows Soviet players to lock down corridors and chokepoints, compensating for the generally open nature of maps like Kursk.',
    },
    {
        id: 'type99-lmg',
        name: 'Type 99 LMG',
        category: 'Assault Rifle',
        affiliation: 'Axis',
        kit: 'Assault',
        nationality: 'Japan',
        mechanism: 'Gas-operated',
        magCapacity: 30,
        totalAmmo: '150 rounds (5 mags)',
        effectiveRange: 'Medium-Long (0-300m)',
        historicalContext: 'The standard Japanese light machine gun, featuring a top-mounted magazine.',
        inGamePerformance: 'Features a 30-round magazine matching the StG 44 in capacity. The top-mounted magazine creates a significant blind spot in the center of the screen, forcing players to aim "around" the obstruction.',
        tacticalAnalysis: 'Despite the visual obstruction, the Type 99 is accurate and powerful. Crucial for Japanese defense on Wake Island, allowing defenders to pick off US Marines attempting to land.',
    },
    {
        id: 'johnson-m1941',
        name: 'Johnson M1941 LMG',
        category: 'Assault Rifle',
        affiliation: 'Allies',
        kit: 'Assault',
        nationality: 'Canada (Patch 1.6)',
        mechanism: 'Short recoil',
        magCapacity: 20,
        totalAmmo: '100 rounds (5 mags)',
        effectiveRange: 'Medium-Long (0-300m)',
        historicalContext: 'Used by the First Special Service Force and US Marines. Added to the Canadian faction in the Liberation of Caen map update (Patch 1.6).',
        inGamePerformance: 'Similar to the BAR with a 20-round magazine, but with a side-mounted magazine profile. Offers a slightly different recoil pattern and faster cyclic rate.',
        tacticalAnalysis: 'A "rush" weapon for the Canadian offensive. The faster rate of fire makes it effective for aggressive pushes but requires the same trigger discipline as the BAR.',
    },

    // === RIFLES ===
    {
        id: 'lee-enfield',
        name: 'Lee-Enfield No. 4 Mk I',
        category: 'Rifle',
        affiliation: 'Allies',
        kit: 'Engineer',
        nationality: 'UK, Canada, US (Europe)',
        mechanism: 'Bolt-action',
        magCapacity: 10,
        totalAmmo: '50 rounds (5 clips)',
        effectiveRange: 'Long (500m+)',
        historicalContext: 'Famous for its smooth bolt action and 10-round magazine—double that of most contemporaries.',
        inGamePerformance: 'The 10-round capacity is a massive advantage. Loaded via two 5-round stripper clips, allowing for sustained engagement. Iron sights are clear with manageable ballistic drop.',
        tacticalAnalysis: 'High capacity makes the British Engineer a formidable combatant, capable of engaging a squad of infantry before needing to reload. Contrasts sharply with the German Engineer\'s 5-round Kar98k.',
    },
    {
        id: 'kar98k',
        name: 'Kar98k',
        category: 'Rifle',
        affiliation: 'Axis',
        kit: 'Engineer',
        nationality: 'Germany',
        mechanism: 'Bolt-action',
        magCapacity: 5,
        totalAmmo: '25 rounds (5 clips)',
        effectiveRange: 'Long (500m+)',
        historicalContext: 'The standard German service rifle, robust and accurate but limited by its 5-round internal magazine.',
        inGamePerformance: 'Deals high damage but hampered by 5-round capacity. Reload animation involves inserting a stripper clip, which can be interrupted.',
        tacticalAnalysis: 'German Engineers must rely on accuracy and positioning. Missing a shot is more punitive due to lower magazine capacity. Encourages a methodical, long-range playstyle.',
    },
    {
        id: 'm1-garand',
        name: 'M1 Garand',
        category: 'Rifle',
        affiliation: 'Allies',
        kit: 'Engineer',
        nationality: 'USMC (Patch 1.6)',
        mechanism: 'Semi-automatic, gas-operated',
        magCapacity: 8,
        totalAmmo: '40 rounds (5 clips)',
        effectiveRange: 'Medium-Long (0-300m)',
        historicalContext: '"The greatest battle implement ever devised" according to General Patton. The Garand gave US infantry a massive firepower advantage with its semi-auto fire.',
        inGamePerformance: 'Added in Patch 1.6 for the Pacific theater. Features an 8-round en-bloc clip. Cannot be reloaded mid-clip; must fire all rounds to trigger the automatic "ping" and reload.',
        tacticalAnalysis: 'Makes the US Engineer superior in medium-range skirmishes. The ability to fire rapid follow-up shots allows Engineers to aggressively push flags and defend demolition charges.',
    },
    {
        id: 'type5',
        name: 'Type 5',
        category: 'Rifle',
        affiliation: 'Axis',
        kit: 'Engineer',
        nationality: 'Japan (Patch 1.6)',
        mechanism: 'Semi-automatic, gas-operated',
        magCapacity: 10,
        totalAmmo: '50 rounds (5 clips)',
        effectiveRange: 'Medium-Long (0-300m)',
        historicalContext: 'A Japanese prototype copy of the M1 Garand, modified to take 10-round stripper clips. Saw extremely limited (if any) combat use.',
        inGamePerformance: 'Introduced to balance the M1 Garand in the Pacific. Features a 10-round magazine (2 more than the Garand). Semi-automatic with stripper clip reload.',
        tacticalAnalysis: 'Levels the playing field for Japanese Engineers. The 10-round capacity allows for one or two extra kills per magazine compared to the Garand.',
    },

    // === SNIPER RIFLES ===
    {
        id: 'sniper-enfield',
        name: 'Sniper No. 4 Mk I',
        category: 'Sniper',
        affiliation: 'Allies',
        kit: 'Scout',
        nationality: 'US, UK',
        mechanism: 'Bolt-action, scoped',
        magCapacity: 10,
        totalAmmo: '30 rounds (3 clips)',
        effectiveRange: 'Extreme (1000m+)',
        historicalContext: 'The scoped variant of the Lee-Enfield No. 4, used by Allied snipers for precision elimination.',
        inGamePerformance: 'Retains the excellent 10-round magazine of the standard Lee-Enfield. High-magnification scope allows for extreme range engagement. Headshots are one-hit kills.',
        tacticalAnalysis: 'The larger magazine gives Allied Scouts more flexibility before needing to reload and expose their position. Ideal for covering chokepoints and eliminating high-value targets.',
    },
    {
        id: 'sniper-kar98k',
        name: 'Sniper Kar98k',
        category: 'Sniper',
        affiliation: 'Axis',
        kit: 'Scout',
        nationality: 'Germany, Japan',
        mechanism: 'Bolt-action, scoped',
        magCapacity: 5,
        totalAmmo: '15 rounds (3 clips)',
        effectiveRange: 'Extreme (1000m+)',
        historicalContext: 'The scoped variant of the Karabiner 98k, used by Wehrmacht and Japanese snipers.',
        inGamePerformance: 'Limited by the 5-round magazine inherited from the standard Kar98k. Requires more careful shot selection due to lower ammo capacity.',
        tacticalAnalysis: 'Axis Scouts must make every shot count. Missing forces an earlier reload, potentially exposing the sniper\'s position. Rewards patience and accuracy.',
    },

    // === ANTI-TANK ===
    {
        id: 'bazooka',
        name: 'M1 Bazooka',
        category: 'Anti-Tank',
        affiliation: 'Allies',
        kit: 'Anti-Tank',
        nationality: 'US, UK, USSR',
        mechanism: 'Rocket launcher',
        magCapacity: 1,
        totalAmmo: '5 rockets',
        effectiveRange: 'Medium (impact)',
        historicalContext: 'The first widely used man-portable anti-tank rocket launcher, firing a shaped charge projectile.',
        inGamePerformance: 'Fires a shaped charge with significant trajectory arc, requiring practice to hit moving tanks at range. Effective against rear armor; often deflects on frontal armor of Tigers.',
        tacticalAnalysis: 'Position for side or rear shots. After firing, immediately switch to pistol for self-defense during the long reload. Use terrain for cover between shots.',
    },
    {
        id: 'panzerschreck',
        name: 'Panzerschreck',
        category: 'Anti-Tank',
        affiliation: 'Axis',
        kit: 'Anti-Tank',
        nationality: 'Germany, Japan',
        mechanism: 'Rocket launcher',
        magCapacity: 1,
        totalAmmo: '5 rockets',
        effectiveRange: 'Medium (impact)',
        historicalContext: 'German anti-tank rocket launcher with distinctive blast shield. Inspired by captured American Bazookas.',
        inGamePerformance: 'Visually distinct with blast shield. Slightly flatter trajectory and higher damage profile against Allied armor compared to the Bazooka.',
        tacticalAnalysis: 'The flatter trajectory makes ranging easier. Particularly effective against Shermans and T-34s. Still requires rear/side shots against heavy armor.',
    },

    // === EXPLOSIVES ===
    {
        id: 'expack',
        name: 'Explosive Pack (Expack)',
        category: 'Explosive',
        affiliation: 'Both',
        kit: 'Engineer',
        nationality: 'All',
        mechanism: 'Remote detonation',
        magCapacity: 0,
        totalAmmo: '4-5 packs',
        effectiveRange: 'Placed',
        historicalContext: 'Satchel charges used for demolition of structures and vehicles.',
        inGamePerformance: 'The most powerful infantry weapon. Can destroy any vehicle in a single blast if placed on the rear deck. Also used to destroy objectives like radar stations and coastal guns.',
        tacticalAnalysis: 'Devastating in urban combat—throw from windows onto tanks below. Can be used for car bombs or placed on bridges for ambushes. Requires timing and positioning.',
    },
    {
        id: 'landmine',
        name: 'Landmine',
        category: 'Explosive',
        affiliation: 'Both',
        kit: 'Engineer',
        nationality: 'All',
        mechanism: 'Pressure-activated',
        magCapacity: 0,
        totalAmmo: '4 mines',
        effectiveRange: 'Placed',
        historicalContext: 'Anti-tank mines designed to disable or destroy vehicles driving over them.',
        inGamePerformance: 'Only triggered by vehicles, not infantry. Visible on the ground but can be hidden in shadows or on slopes. A cluster of 2-3 mines ensures kills on heavy tanks.',
        tacticalAnalysis: 'Essential for chokepoint defense. Place at crests of inclines or around blind corners to maximize surprise. Can be disarmed with wrench by enemy engineers.',
    },
];

// Get weapons by category
export function getWeaponsByCategory(category: string): DetailedWeapon[] {
    return detailedWeapons.filter(w => w.category === category);
}

// Get weapon by ID
export function getWeaponById(id: string): DetailedWeapon | undefined {
    return detailedWeapons.find(w => w.id === id);
}

// Category order for display
export const weaponCategories = [
    { id: 'Sidearm', name: 'Sidearms', description: 'The last line of defense' },
    { id: 'SMG', name: 'Submachine Guns', description: 'The Medic\'s tool for close-quarters combat' },
    { id: 'Assault Rifle', name: 'Assault Rifles & LMGs', description: 'Heavy firepower for the Assault class' },
    { id: 'Rifle', name: 'Rifles', description: 'Precision instruments for Engineers' },
    { id: 'Sniper', name: 'Sniper Rifles', description: 'Long-range elimination for Scouts' },
    { id: 'Anti-Tank', name: 'Anti-Tank Weapons', description: 'Infantry solutions for destroying armor' },
    { id: 'Explosive', name: 'Explosives', description: 'Demolition tools for Engineers' },
];
